on:
  push:
    branches: ["main"]
  
jobs:
  steps:
    - name: AWS CLI v2
      uses: imehedi/actions-awscli-v2@latest
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"

      run: aws help
